	

name: bicycle

on:
  push:
    branches:
      - main

jobs:
  karanDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: git library
        uses: actions/checkout@v4
      - name: connection
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{secrets.IP}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}

          script: |
            cd /home/karan/Backend
            git pull origin main
            sudo npm i
            pm2 start index.js -- name "backend"
